
evenement:
    path:     /evenement
    defaults: { _controller: AssociationGestionAssociationBundle:Default:evenement }

evendetail:
    path:     /evendetail
    defaults: { _controller: AssociationGestionAssociationBundle:Default:evendetail }

evenmeduim:
    path:     /evenmeduim
    defaults: { _controller: AssociationGestionAssociationBundle:Default:evenmeduim }

modsuppevenn:
    path:     /modsuppevenn
    defaults: { _controller: AssociationGestionAssociationBundle:Default:modsuppevenn }

moddetaileven:
    path:     /moddetaileven
    defaults: { _controller: AssociationGestionAssociationBundle:Default:moddetaileven }

ajouteven:
    path:     /ajouteven
    defaults: { _controller: AssociationGestionAssociationBundle:Default:ajouteven }

accueilAdmin:
    path:     /accueilAdmin
    defaults: { _controller: AssociationGestionAssociationBundle:admin:acceuil }
evenementAdmin:
    path:     /evenementAdmin
    defaults: { _controller: AssociationGestionAssociationBundle:admin:associationAdmin }
