ajoutmag:
    path:     /ajoutmag
    defaults: { _controller: StoreGestionProduitsBundle:Default:ajoutmag }

produit:
    path:     /produit
    defaults: { _controller: StoreGestionProduitsBundle:Default:produit }

slideproduit:
    path:     /slideproduit
    defaults: { _controller: StoreGestionProduitsBundle:Default:slideproduit }

produitdetail:
    path:     /produitdetail
    defaults: { _controller: StoreGestionProduitsBundle:Default:produitdetail }

modsuppstore:
    path:     /modsuppstore
    defaults: { _controller: StoreGestionProduitsBundle:Default:modsuppstore }

modifdetailmag:
    path:     /modifdetailmag
    defaults: { _controller: StoreGestionProduitsBundle:Default:modifdetailmag }

accueilProduit:
    path:     /accueilProduit
    defaults: { _controller: StoreGestionProduitsBundle:admin:acceuilProduit }
produitAdmin:
    path:     /produitAdmin
    defaults: { _controller: StoreGestionProduitsBundle:admin:produitAdmin }
