
veterinaire:
    path:     /veterinaire
    defaults: { _controller: VeterinaireGestionRDVBundle:Default:veterinaire }

veterinairedetail:
    path:     /veterinairedetail
    defaults: { _controller: VeterinaireGestionRDVBundle:Default:veterinairedetail }


espaceveterinaire:
    path:     /espaceveterinaire
    defaults: { _controller: VeterinaireGestionRDVBundle:Default:espaceveterinaire }

rendezvous:
    path:     /rendezvous
    defaults: { _controller: VeterinaireGestionRDVBundle:Default:rendezvous }


accueilAdmin:
    path:     /accueilAdmin
    defaults: { _controller: VeterinaireGestionRDVBundle:admin:acceuil }
veterinaireAdmin:
    path:     /veterinaireAdmin
    defaults: { _controller: VeterinaireGestionRDVBundle:admin:veterinaireAdmin }
